### ISSUE TITLE
locking is ineffective

### ISSUE THREAD

**Issue by mgerdts** [joyent/mdata-client#11]
I've spent a bit of time chasing down problems with `cloud-init` on CentOS.  cloud-init has its own implementation of the metadata protocol.  The system already had [sdc-vmtools](https://github.com/joyent/sdc-vmtools) installed, so `/etc/rc.d/rc.local` was invoking `mdata-get` many times.  As luck would have it, `cloud-init` and `mdata-get` were accessing the serial port at the same time.  Details in [launchpad 1746605](https://bugs.launchpad.net/cloud-init/+bug/1746605).

Currently `mdata-get` and related commands try to lock with:

```
        /*
         * Lock the serial port for exclusive access:
         */
        l.l_type = F_WRLCK;
        l.l_whence = SEEK_SET;
        l.l_start = l.l_len = 0;
        if (fcntl(fd, F_SETLKW, &l) == -1) {
                *errmsg = "Could not lock serial device.";
                return (-1);
        }
```

But apparently that is not [the Linux way](http://www.tldp.org/HOWTO/Serial-HOWTO-13.html).

**Comment by jclulow** [comment]
Groan.

**Comment by mgerdts** [comment]
After looking a bit further, I see that the tldp.org page I linked above seems to be out of step with reality.  On CentOS 7, `minicom` does not create a lock file in `/var/locks` - it uses the same mechanism that `mdata-get` is using.

[Debian 734086](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=734086) suggests that the `/var/locks` approach is considered obsolete.  The [`lockdev`](https://linux.die.net/man/3/lockdev) library that it refers to is not installed on CentOS 7 or Ubuntu 17.10.

Based on this, I'm closing this bug and will modify `cloud-init` to use locks that are compatible with `mdata-get` and `minicom`.
