### ISSUE TITLE
Fix mdata-list man page information about operation

### ISSUE THREAD

**Issue by shaikmanu797** [joyent/mdata-client#13]
The man page for mdata-list says it fetches key-value pairs and emits the output to stdout, whereas actually it just outputs the keys of the metadata.

https://github.com/joyent/mdata-client/blob/master/man/man1m/mdata-list.1m

**Comment by shaikmanu797** [comment]
https://smartos.org/man/1M/mdata-list

**Comment by bahamat** [comment]
The specific text is:

> **mdata-list** -- Fetch the list of available metadata key-value pairs.

I don't consider that it's inaccurate to say that it's a *list* of key-value pairs.

**Comment by shaikmanu797** [comment]
It's a bit confusing as the return output is just a list of metadata keys.
