### ISSUE TITLE
Avoid delay closing serial line on NetBSD

### ISSUE THREAD

**Issue by jperkin** [joyent/mdata-client#15]
When running any mdata command on NetBSD, there is a noticeable 1 second delay on exit while the serial line file descriptor is being closed.

After some digging into the termios flags, I determined that clearing the `HUPCL` bit avoids the delay.

```diff
diff --git a/plat/unix_common.c b/plat/unix_common.c
index 731263e..0a37dbb 100644
--- a/plat/unix_common.c
+++ b/plat/unix_common.c
@@ -39,6 +39,7 @@ unix_raw_mode(int fd, char **errmsg)
        tios.c_iflag &= ~(BRKINT | ICRNL | INPCK | ISTRIP | IXON);
        tios.c_oflag &= ~(OPOST);
        tios.c_cflag |= (CS8);
+       tios.c_cflag &= ~(HUPCL);
        tios.c_lflag &= ~(ECHO | ICANON | IEXTEN | ISIG);
 
        /*
```

Before:

```shell
$ time mdata-list
root_authorized_keys
        1.09 real         0.00 user         0.00 sys
```

After:

```shell
$ time mdata-list
root_authorized_keys
        0.09 real         0.00 user         0.00 sys
```

I'll submit a pull request for this, but would appreciate review from @jclulow and anyone else who knows their TTY stuff.  I'll also verify this doesn't cause regressions on the other BSDs (I already verified it's fine on SmartOS).

**Comment by jperkin** [comment]
It's also perhaps worth noting that we don't perform an explicit `plat_fini()` anywhere after successful reads.  We might want to add a `proto_close()` or similar to do this rather than leaving the exit handler to do it all.

**Comment by jclulow** [comment]
I am not particularly familiar with `HUPCL`, but I agree it probably makes sense to turn it off for this.  I don't know that KVM or bhyve usefully emulate the DTR signal of a real serial port in any useful way.

**Comment by bahamat** [comment]
Can you also test this with Linux in lx/kvm/bhyve? I’m inclined to approve this, but just want to sanity check that it hasn’t caused an issue elsewhere.

**Comment by jperkin** [comment]
Sure.

CentOS 8 on bhyve:

```shell
$ uname -rs
Linux 4.18.0-147.8.1.el8_1.x86_64

$ time mdata-get sdc:brand
bhyve

real	0m0.115s
user	0m0.001s
sys	0m0.005s

$ time ./mdata-get sdc:brand
bhyve

real	0m0.115s
user	0m0.002s
sys	0m0.004s
```

CentOS 6 on KVM:

```shell
$ uname -rs
Linux 2.6.32-754.35.1.el6.x86_64

$ time mdata-get sdc:brand
kvm

real	0m0.142s
user	0m0.003s
sys	0m0.006s

$ time ./mdata-get sdc:brand
kvm

real	0m0.126s
user	0m0.001s
sys	0m0.005s
```

On LX the native `mdata-*` are used:

```shell
$ ls -l /usr/bin/mdata-*
lrwxrwxrwx 1 root root 29 Oct 16 21:44 /usr/bin/mdata-delete -> /native/usr/sbin/mdata-delete
lrwxrwxrwx 1 root root 26 Oct 16 21:44 /usr/bin/mdata-get -> /native/usr/sbin/mdata-get
lrwxrwxrwx 1 root root 27 Oct 16 21:44 /usr/bin/mdata-list -> /native/usr/sbin/mdata-list
lrwxrwxrwx 1 root root 26 Oct 16 21:44 /usr/bin/mdata-put -> /native/usr/sbin/mdata-put
```

So to test those I used my SmartOS KVM hosts to verify that the access via `/dev/term/b` still works:

```
$ uname -rsv
SunOS 5.11 joyent_20161222T003450Z

$ time mdata-get sdc:brand
kvm

real    0m0.135s
user    0m0.001s
sys     0m0.004s

$ time ./mdata-get sdc:brand
kvm

real    0m0.138s
user    0m0.001s
sys     0m0.005s
```

**Comment by jperkin** [comment]
I've also tested on FreeBSD/KVM:

```shell
$ uname -rs
FreeBSD 12.0-RELEASE-p3

$ time mdata-get sdc:brand
kvm
0.000u 0.002s 0:00.13 0.0%	0+0k 0+0io 0pf+0w

time ./mdata-get sdc:brand
kvm
0.000u 0.002s 0:00.22 0.0%	0+0k 0+0io 0pf+0w
```

Our OpenBSD image is so old you can no longer install packages on it as the release (6.1) was archived a long time ago, but I managed to build it manually and it also works fine:

```shell
$ uname -rs
OpenBSD 6.1

$ time mdata-get sdc:brand
kvm
    0m00.16s real     0m00.00s user     0m00.02s system

time ./mdata-get sdc:brand
kvm
    0m00.14s real     0m00.00s user     0m00.01s system
```

So it appears this is only an issue on NetBSD, I was rather expecting OpenBSD to exhibit the same problem.

**Comment by bahamat** [comment]
Awesome.
