### ISSUE TITLE
mdata-fetch should not blindly try to remove a file

### ISSUE THREAD

**Issue by sjorge** [joyent/mdata-client#6]
```
[2016-03-29T17:05:27Z] /lib/svc/method/mdata-fetch:421: rm /etc/inet/static_routes.vmadm
rm: /etc/inet/static_routes.vmadm: No such file or directory
```

Checking if the file exists before trying to remove it would probably be better. (I'm not 100% I got the correct repo for this one)

**Comment by chorrell** [comment]
I think maybe this should be moved to the SmartOS repo although the above looks like it's from code in zoneinit

**Comment by sjorge** [comment]
I was indeed not sure if i needed smartos-live or this repo. I'll recreate it there.
